apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction
        image: eu.gcr.io/rugged-shuttle-195322/transaction-api:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwt
---
kind: Service
apiVersion: v1
metadata:
  name: transaction
spec:
  selector:
    app: transaction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-deployment
  labels:
    app: loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      containers:
      - name: loyalty
        image: eu.gcr.io/rugged-shuttle-195322/loyalty-worker:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: eu.gcr.io/rugged-shuttle-195322/auth-api:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwt
---
kind: Service
apiVersion: v1
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---                ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        ports:
        - containerPort: 6379
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 20
          periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  